# Generated by Django 3.1.4 on 2021-01-07 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=200)),
                ('ItemQuantity', models.TextField()),
                ('ItemStatus', models.CharField(max_length=15)),
                ('Date', models.DateField()),
                ('UserId', models.IntegerField()),
            ],
        ),
    ]
