# Generated by Django 3.1.4 on 2021-01-08 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_auto_20210108_0530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grocery',
            name='ItemStatus',
            field=models.IntegerField(),
        ),
    ]
